name: test_execution

on:
  workflow_call:
    inputs:
      input-value:
        description: 'An input-value has been passed from caller workflow'
        required: true
        type: string

#    secrets:
#      SOME_SECRET:
#        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: mirandaxyrus13/test-automation-framework
          ref: 'main'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.4

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: GitHub Event Repo Name
        run: echo "${{ github.event.repository.name }}"

      - name: Build with Maven and Regression Test of SauceDemo suite ${{inputs.input-value}} triggered by repository - ${{ github.event.repository.name }}
        run: mvn clean test -DsuiteXmlFile="${{inputs.input-value}}" -Denvironment="test" -DbrowserInstance="chrome"